Rifqi/mycite treatment descriptives
Holmusk/otsuka_nov21_sow_feasibility pull request #13
Opened 2021-11-25 11:39 UTC by RifqiAlkhatib

descriptives saved into csv. Stitched prescriptions also saved into csv if need to use it again

2021-12-05 07:40 UTC, soonnnanh requested changes
Why are the jupyter notebooks pushed into the repo? Besides that and the addition of 1 day that I see in the duration of treatment prescription lines, well done code. 

Note: Please document your code with descriptions of the code and your arguments in the main mycite repo

2021-12-05 07:40 UTC, soonnnanh commented on src/modules/myciteTreatmentDescriptives/myciteTreatmentDescriptives.py
> +    ).dt.days + 1
Why do you plus one here?

2021-12-05 07:40 UTC, soonnnanh commented on src/modules/myciteTreatmentDescriptives/myciteTreatmentDescriptives.py
> +
If we do a groupby on the non-stitched treatment data, and get the duration we will be using the sum of the duration of the treatments even if multiple prescriptions overlap. E.g. If we have 1 prescription from 1/Jan to 30/Jun, and another prescription from 1/Feb to 30/July, assuming each month is 30 days, the total prescription duration for the patient will be 180 + 180 = 360 days. Make this clear either in the function documentation or somewhere

2021-12-05 07:40 UTC, soonnnanh commented on src/modules/myciteTreatmentDescriptives/myciteTreatmentDescriptives.py
> +            current_treatment['treatment_duration_days'] = (row['end_date'] - row['start_date']).days + 1
Remove the + 1

2021-12-05 07:40 UTC, soonnnanh commented on src/modules/myciteTreatmentDescriptives/myciteTreatmentDescriptives.py
> +                    ).days + 1
Remove the + 1

2021-12-05 07:40 UTC, soonnnanh commented on src/modules/myciteTreatmentDescriptives/myciteTreatmentDescriptives.py
> +    df_out['gap_days'] = (df_out['start_date'] - df_out['end_date'].shift(1)).dt.days
Dont need to add 1 to the day

2021-12-09 06:27 UTC, RifqiAlkhatib commented
@soonnnanh Removed notebooks and added documentation so that its clear. +1 days to remain as discussed, should be ok to merge now

2021-12-13 02:31 UTC, soonnnanh approved these changes

2021-12-13 02:31 UTC, merged